plugins {
    id 'java'
    id 'maven-publish'
}

group = 'com.github.shineware'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    implementation 'com.github.shineware:commons:1.0.1'
    implementation 'com.github.shineware:aho-corasick:1.1.0'
    testImplementation 'junit:junit:4.12'
}

tasks.register('uberJar', Jar) {
    archiveAppendix = 'uber'

    from sourceSets.main.output
    from configurations.runtimeClasspath
            .findAll { it.name.endsWith('jar') }
            .collect { zipTree(it) }
}

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

test {
    testLogging {
        showStandardStreams = true
    }
}
